cv:
  name: Andrei Zaitsev
  label: Senior Software Engineer
  location: North Holland, Amsterdam
  email: andrey.zayitsev@gmail.com
  phone: '+31681050223'
  # website: null
  # social_networks:
  #   - network: GitHub
  #     username: johndoe
  #   - network: LinkedIn
  #     username: johndoe
  summary: I am a motivated (haha, no) Mechanical Engineer with a strong academic record from prestigious institutions and practical experience in innovative environments like CERN. My specialization lies in the design, simulation, and implementation of mechanical systems, especially in robotics and finite element analysis. I possess strong technical skills, approach problems proactively, and am dedicated to innovation. I excel in team settings where I can contribute to significant projects and promote advancements in engineering.
  cover_letter:
    company: DreamTeam Corporation
    body: As an accomplished mechanical engineer with a strong foundation in both theoretical and practical aspects of the field, my expertise spans from innovative project design to in-depth research and development. My academic and professional journey has been marked by a series of successful projects, including the creation of sophisticated robotic systems and contributing to groundbreaking research at CERN. My passion for engineering is matched by my commitment to delivering results that exceed expectations. I am excited about the opportunity to bring my blend of experience, skills, and dedication to DreamTeamInc., where I aim to contribute to and thrive in your dynamic engineering environment.
  section_order:
    - Education
    - Work Experience
    - Academic Projects
    - Certificates
    - Personal Projects
    - Skills
    - Test Scores
    - Extracurricular Activities
    - Publications
    - My Custom Section
    - My Other Custom Section
    - My Third Custom Section
    - My Final Custom Section
  education:
    - institution: My University
      url: https://boun.edu.tr
      area: Mechanical Engineering
      study_type: BS
      location: Ankara, Türkiye
      start_date: '2017-09-01'
      end_date: '2023-01-01'
      transcript_url: https://example.com
      gpa: 3.99/4.00
      highlights:
        - 'Class rank: 1 of 62'
    - institution: The University of Texas at Austin
      url: https://utexas.edu
      area: Mechanical Engineering, Student Exchange Program
      location: Austin, TX, USA
      start_date: '2021-08-01'
      end_date: '2022-01-15'
      transcript_url: https://example.com
      gpa: 4.00/4.00
  work_experience:
    - company: CERN
      position: Mechanical Engineer
      location: Geneva, Switzerland
      url: https://home.cern
      start_date: '2023-02-01'
      end_date: present
      highlights:
        - CERN is a research organization that operates the world's largest and most powerful particle accelerator.
    - company: AmIACompany
      position: Summer Intern
      location: Istanbul, Türkiye
      url: https://example.com
      start_date: '2022-06-15'
      end_date: '2022-08-01'
      highlights:
        - AmIACompany is a technology company that provides web-based engineering applications that enable the simulation and optimization of products and manufacturing tools.
        - Modeled and simulated a metal-forming process deep drawing using finite element analysis with open-source software called CalculiX.
  academic_projects:
    - name: Design and Construction of a Robot
      location: Istanbul, Türkiye
      date: Fall 2022
      highlights:
        - Designed and constructed a controllable robot that measures a car's torque and power output at different speeds for my senior design project.
      url: https://example.com
    - name: Design and Construction of an Another Robot
      location: Istanbul, Türkiye
      date: Fall 2020
      highlights:
        - Designed, built, and programmed a microcontroller-based device that plays a guitar with DC motors as part of a mechatronics course term project.
      url: https://example.com
  publications:
    - title: Phononic band gaps induced by inertial amplification in periodic media
      authors:
        - Author 1
        - John Doe
        - Author 3
      journal: Physical Review B
      doi: 10.1103/PhysRevB.76.054309
      date: '2007-08-01'
      cited_by: 243
  certificates:
    - name: Machine Learning by Stanford University
      date: '2022-09-01'
      url: https://example.com
  skills:
    - name: Programming
      details: C++, C, Python, JavaScript, MATLAB, Lua, LaTeX
    - name: OS
      details: Windows, Ubuntu
    - name: Other tools
      details: Git, Premake, HTML, CSS, React
    - name: Languages
      details: English (Advanced), French (Lower Intermediate), Turkish (Native)
  test_scores:
    - name: TOEFL
      date: '2022-10-01'
      details: '113/120 — Reading: 29/30, Listening: 30/30, Speaking: 27/30, Writing: 27/30'
      url: https://example.com
    - name: GRE
      details: 'Verbal Reasoning: 160/170, Quantitative Reasoning: 170/170, Analytical Writing: 5.5/6'
      url: https://example.com
  personal_projects:
    - name: Ray Tracing in C++
      date: Spring 2021
      highlights:
        - Coded a ray tracer in C++ that can render scenes with multiple light sources, spheres, and planes with reflection and refraction properties.
      url: https://example.com
  extracurricular_activities:
    - company: Dumanlikiz Skiing Club
      position: Co-founder / Skiing Instructor
      location: Chamonix, France
      date: Summer 2017 and 2018
      highlights:
        - Taught skiing during winters as a certified skiing instructor.
  custom_sections:
    - title: My Custom Section
      entry_type: OneLineEntry
      entries:
        - name: Testing custom sections
          details: Wohooo!
        - name: This is a
          details: OneLineEntry!
    - title: My Other Custom Section
      entry_type: EducationEntry
      entries:
        - institution: Hop!
          area: Hop!
          study_type: HA
          highlights:
            - 'There are only five types of entries: *EducationEntry*, *ExperienceEntry*, *NormalEntry*, *OneLineEntry*, and *PublicationEntry*.'
            - This is an EducationEntry!
          start_date: '2022-06-15'
          end_date: '2022-08-01'
    - title: My Third Custom Section
      entry_type: ExperienceEntry
      entries:
        - company: Hop!
          position: Hop!
          date: My Date
          location: My Location
          highlights:
            - I think this is really working. This is an *ExperienceEntry*!
    - title: My Final Custom Section
      entry_type: NormalEntry
      link_text: My Link Text
      entries:
        - name: This is a normal entry!
          url: https://example.com
          highlights:
            - You don't have to specify a *date* or **location** every time.
            - You can use *Markdown* in the **highlights**!
            - 'Special characters test: üğç'
design:
  theme: classic
  font: SourceSans3
  font_size: 10pt
  page_size: a4paper
  options:
    primary_color: rgb(0,79,144)
    date_and_location_width: 3.6 cm
    show_timespan_in:
      - Work Experience
      - My Other Custom Section
    show_last_updated_date: true
    text_alignment: justified
    header_font_size: 30 pt
    margins:
      page:
        top: 2 cm
        bottom: 2 cm
        left: 1.24 cm
        right: 1.24 cm
      section_title:
        top: 0.2 cm
        bottom: 0.2 cm
      entry_area:
        left_and_right: 0.2 cm
        vertical_between: 0.2 cm
      highlights_area:
        top: 0.10 cm
        left: 0.4 cm
        vertical_between_bullet_points: 0.10 cm
      header:
        vertical_between_name_and_connections: 0.2 cm
        bottom: 0.2 cm
