name: Build PR
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CV and cover letter
    steps:
      - uses: actions/checkout@v2
      - name: Use Streamline CV GitHub Action
        uses: Streamline-CV/gh-action-build@main
  check:
    runs-on: ubuntu-latest
    name: Check CV
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Check CV
        uses: Streamline-CV/gh-action-check@main
        with:
          githubKey: ${{ secrets.GITHUB_TOKEN }}
  review:
    runs-on: ubuntu-latest
    name: Review CV
    steps:
      - uses: actions/checkout@v2
      - name: Review CV
        uses: Streamline-CV/gh-action-aireview@main
        with:
          openaiKey: ${{ secrets.OPENAI_API_KEY }}
          githubKey: ${{ secrets.GITHUB_TOKEN }}