name: Build PR
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CV and cover letter
    steps:
      - uses: actions/checkout@v2
      - name: Use Streamline CV GitHub Action
        uses: achugr/streamline-cv-gh-action-build@main