name: Review CV
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Review CV
    steps:
      - uses: actions/checkout@v2
      - name: Review CV
        uses: Streamline-CV/gh-action-aireview@main
        with:
          openaiKey: ${{ secrets.OPENAI_API_KEY }}
          githubKey: ${{ secrets.GITHUB_TOKEN }}
